name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout project
      uses: actions/checkout@v2
      with:
        submodules: false
    - name: find latest version of janet
      uses: oprypin/find-latest-tag@v1
      with:
        repository: janet-lang/janet
        releases-only: true
        prefix: 'v'
      id: janet-ver
    - name: download janet
      run: curl -LO https://github.com/janet-lang/janet/releases/download/${{ steps.janet-ver.outputs.tag }}/janet-${{ steps.janet-ver.outputs.tag }}-linux.tar.gz
    - name: extract janet
      run: tar -xvzf janet-${{ steps.janet-ver.outputs.tag }}-linux.tar.gz
    - name: add directory to path
      run: echo "janet-${{ steps.janet-ver.outputs.tag }}-linux/bin" >> $GITHUB_PATH
    - name: make modules directory
      run: mkdir modules
    - name: set JANET_PATH
      run: echo "JANET_PATH=modules" >> $GITHUB_ENV
    - name: set JANET_LIBPATH
      run: echo "JANET_LIBPATH=janet-${{ steps.janet-ver.outputs.tag }}-linux/lib" >> $GITHUB_ENV
    - name: set JANET_HEADERPATH
      run: echo "JANET_HEADERPATH=janet-${{ steps.janet-ver.outputs.tag }}-linux/include" >> $GITHUB_ENV
    - name: install dependencies
      run: /usr/bin/env jpm deps
    - name: run tests
      run: /usr/bin/env jpm test
